### ISSUE TITLE
Not able to connect to AWS

### ISSUE THREAD

**Issue by toashwin** [kamilfb/mqtt-spy#102]
When I try to connect to AWS, I am getting following crash. 
I have attached my xls file. 
I am not attaching the certificate files. and also modified the aws URI in the xml file attached.

I am using TLS1.2, provided paths to root_ca file, crt file and key file. Did not provide any value for the password. 

these certificates work with my device..  But could not test with MQTT-spy.

pl.baczkowicz.spy.exceptions.ConfigurationException: Invalid configuration parameters
    at pl.baczkowicz.mqttspy.connectivity.MqttConnectionDetailsWithOptions.<init>(MqttConnectionDetailsWithOptions.java:91)
    at pl.baczkowicz.mqttspy.connectivity.MqttRuntimeConnectionProperties.<init>(MqttRuntimeConnectionProperties.java:34)
    at pl.baczkowicz.mqttspy.ui.MqttConnectionViewManager.openConnection(MqttConnectionViewManager.java:152)
    at pl.baczkowicz.mqttspy.ui.controllers.EditMqttConnectionController$6.run(EditMqttConnectionController.java:461)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Unknown Source)
Caused by: pl.baczkowicz.spy.exceptions.SpyException: Cannot create TLS/SSL connection
    at pl.baczkowicz.spy.security.SecureSocketFactoryBuilder.getSocketFactory(SecureSocketFactoryBuilder.java:106)
    at pl.baczkowicz.mqttspy.connectivity.MqttConnectionDetailsWithOptions.populateMqttConnectOptions(MqttConnectionDetailsWithOptions.java:175)
    at pl.baczkowicz.mqttspy.connectivity.MqttConnectionDetailsWithOptions.<init>(MqttConnectionDetailsWithOptions.java:87)
    ... 10 more
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: invalid key format
    at sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(Unknown Source)
    at java.security.KeyFactory.generatePrivate(Unknown Source)
    at pl.baczkowicz.spy.security.SecureSocketUtils.loadPrivateKeyFromPemFile(SecureSocketUtils.java:103)
    at pl.baczkowicz.spy.security.SecureSocketUtils.getKeyManagerFactory(SecureSocketUtils.java:192)
    at pl.baczkowicz.spy.security.SecureSocketFactoryBuilder.getSocketFactory(SecureSocketFactoryBuilder.java:99)
    ... 12 more
Caused by: java.security.InvalidKeyException: invalid key format
    at sun.security.pkcs.PKCS8Key.decode(Unknown Source)
    at sun.security.pkcs.PKCS8Key.decode(Unknown Source)
    at sun.security.rsa.RSAPrivateCrtKeyImpl.<init>(Unknown Source)
    at sun.security.rsa.RSAPrivateCrtKeyImpl.newKey(Unknown Source)
    at sun.security.rsa.RSAKeyFactory.generatePrivate(Unknown Source)
    ... 17 more

[mqtt-spy-configuration.zip](https://github.com/kamilfb/mqtt-spy/files/504838/mqtt-spy-configuration.zip)

**Comment by kamilfb** [comment]
Hi. Which version are you using?

**Comment by toashwin** [comment]
I used the latest version..  0.6.0 beta (build52)
I was getting similar error in other versions as well... 0.5.3 and 0.5.4

**Comment by kjordan-sa** [comment]
I am having similar issues. I m unable to get a connection established. I have tried all the various form of Security settings that I can think of to try and have no luck.

**Comment by kamilfb** [comment]
hi @toashwin, have you tried the settings outlined in https://github.com/eclipse/paho.mqtt-spy/issues/4 ?

**Comment by MihirGangoly** [comment]
Dear Kamil,

I am having this same problem. Any idea how this was resolved? using the eclipse/paho.mqtt-spy#4 link was not great as it asked to install the JAVA Developer and that created other issues with the apps that require the JR.
