### ISSUE TITLE
Unsupported class version error

### ISSUE THREAD

**Issue by ealvarez-accedo** [kamilfb/mqtt-spy#128]
Hello,

I'm trying to run the latest version of worldographer using openjdk8.0 and openjfx 8u60, using the following command line invocation:

`java -Xmx4G -jar worldographer.jar`

I then get the following error message:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/inkwellideas/ographer/ui/Worldographer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by ealvarez-accedo** [comment]
Please disregard. The problem lied with conflicting version of openjdk coexisting in the machine.
