### ISSUE TITLE
Oracle JRE bug - JavaFX crashes when sorting summary table

### ISSUE THREAD

**Issue by kamilfb** [kamilfb/mqtt-spy#40]
Subscribe to a lot of messages, then sort the summary table.

2015-07-02 14:45:08,144 ERROR [MqttSpyUncaughtExceptionHandler]  - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at javafx.collections.transformation.SortedList.removeFromMapping(Unknown Source)
        at javafx.collections.transformation.SortedList.addRemove(Unknown Source)
        at javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
        at javafx.collections.transformation.TransformationList.lambda$getListener$15(Unknown Source)
        at javafx.collections.transformation.TransformationList$$Lambda$296/584006039.onChanged(Unknown Source)
        at javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
        at javafx.collections.ObservableListBase.fireChange(Unknown Source)
        at javafx.collections.ListChangeBuilder.commit(Unknown Source)
        at javafx.collections.ListChangeBuilder.endChange(Unknown Source)
        at javafx.collections.ObservableListBase.endChange(Unknown Source)
        at javafx.collections.transformation.FilteredList.sourceChanged(Unknown Source)
        at javafx.collections.transformation.TransformationList.lambda$getListener$15(Unknown Source)
        at javafx.collections.transformation.TransformationList$$Lambda$296/584006039.onChanged(Unknown Source)
        at javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
        at javafx.collections.ObservableListBase.fireChange(Unknown Source)
        at javafx.collections.ListChangeBuilder.commit(Unknown Source)
        at javafx.collections.ListChangeBuilder.endChange(Unknown Source)
        at javafx.collections.ObservableListBase.endChange(Unknown Source)
        at javafx.collections.ModifiableObservableListBase.set(Unknown Source)
        at pl.baczkowicz.mqttspy.storage.summary.ObservableTopicSummary.addMessage(ObservableTopicSummary.java:60)
        at pl.baczkowicz.mqttspy.events.queuable.UIEventHandler.showUpdates(UIEventHandler.java:90)
        at pl.baczkowicz.mqttspy.events.queuable.UIEventHandler.access$0(UIEventHandler.java:71)
        at pl.baczkowicz.mqttspy.events.queuable.UIEventHandler$1.run(UIEventHandler.java:58)
        at com.sun.javafx.application.PlatformImpl.lambda$null$170(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$48/1724943951.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(Unknown Source)
        at com.sun.javafx.application.PlatformImpl$$Lambda$47/1645995473.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$145(Unknown Source)
        at com.sun.glass.ui.win.WinApplication$$Lambda$36/1030870354.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by kamilfb** [comment]
This doesn't seem to affect the subscription topic column.

**Comment by kamilfb** [comment]
Tested with the new Java 8 Update 60 and it's working fine now. No changes in mqtt-spy.
