### ISSUE TITLE
No default configuration file  found ERROR

### ISSUE THREAD

**Issue by FallenRiteMonk** [kamilfb/mqtt-spy#46]
Hy,
just tried version 0.2.0 (jar with dependencies) but clicking on the "No default configuration file  found" messages results in a java.lang.NoClassDefFoundError.
Windows 7 64 bit
java 1.8.0_60

Full log:

2015-08-28 15:18:13,942 INFO  [JavaFX Application Thread     ] [MainController                ]  - Default configuration file present (C:\Users\<USER>\mqtt-spy\mqtt-spy-configuration.xml) = false
2015-08-28 15:18:48,728 ERROR [JavaFX Application Thread     ] [MqttSpyUncaughtExceptionHandler]  - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.NoClassDefFoundError: com/sun/javafx/Utils
java.lang.NoClassDefFoundError: com/sun/javafx/Utils
	at org.controlsfx.tools.Platform.getCurrentPlatform(Platform.java:65)
	at org.controlsfx.tools.Platform.<clinit>(Platform.java:41)
	at org.controlsfx.dialog.HeavyweightDialog.<clinit>(HeavyweightDialog.java:70)
	at org.controlsfx.dialog.Dialog.<init>(Dialog.java:340)
	at org.controlsfx.dialog.Dialog.<init>(Dialog.java:319)
	at org.controlsfx.dialog.CustomDialog.<init>(CustomDialog.java:64)
	at org.controlsfx.dialog.CustomDialogs.buildDialog(CustomDialogs.java:396)
	at org.controlsfx.dialog.CustomDialogs.buildDialog(CustomDialogs.java:387)
	at org.controlsfx.dialog.CustomDialogs.showCommandLinks(CustomDialogs.java:249)
	at pl.baczkowicz.mqttspy.ui.utils.DialogUtils.showDefaultConfigurationFileMissingChoice(DialogUtils.java:401)
	at pl.baczkowicz.mqttspy.ui.ControlPanelController$2.handle(ControlPanelController.java:229)
	at pl.baczkowicz.mqttspy.ui.ControlPanelController$2.handle(ControlPanelController.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.scene.control.Button.fire(Unknown Source)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.scene.Scene$MouseHandler.access$1500(Unknown Source)
	at javafx.scene.Scene.impl_processMouseEvent(Unknown Source)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$355(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$149(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.Utils
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 63 more

**Comment by kamilfb** [comment]
Hi. 

This is because you're using incompatible versions of Java and mqtt-spy.

Version 0.2.0 is only compatible with 8u20 up to 8u51.
Version 0.3.0 (currently in beta) is compatible with 8u40 and above.

See the following link for more detail: https://github.com/kamilfb/mqtt-spy/issues/45

To use mqtt-spy with your version of Java (8u60) I suggest you use the latest 0.3.0 beta.
