### ISSUE TITLE
parseMessageLog Null Pointer Exception

### ISSUE THREAD

**Issue by avine01** [kamilfb/mqtt-spy#55]
When attempting to run a script to replay a message log (see attached files), the following exception is being raised:
[Logs.zip](https://github.com/kamilfb/mqtt-spy/files/78652/Logs.zip)

java.lang.NullPointerException
        at pl.baczkowicz.mqttspy.logger.MqttMessageLogParserUtils.parseMessageLog(MqttMessageLogParserUtils.java:121)
        at pl.baczkowicz.mqttspy.logger.MqttMessageLogParserUtils.readAndConvertMessageLog(MqttMessageLogParserUtils.java:61)
        at pl.baczkowicz.mqttspy.logger.MqttMessageLogIO.readFromFile(MqttMessageLogIO.java:60)
        at jdk.nashorn.internal.scripts.Script$Recompilation$9$19$\^eval\_.replay(<eval>:9)
        at jdk.nashorn.internal.scripts.Script$8$\^eval\_.:program(<eval>:49)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:640)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at pl.baczkowicz.spy.scripts.ScriptRunner.runScript(ScriptRunner.java:138)
        at pl.baczkowicz.spy.scripts.ScriptRunner.run(ScriptRunner.java:99)
        at java.lang.Thread.run(Unknown Source)

**Comment by kamilfb** [comment]
Fixed in 0.4.0 beta (build 7). Many thanks for reporting this.
