### ISSUE TITLE
Exception when running test case script

### ISSUE THREAD

**Issue by avine01** [kamilfb/mqtt-spy#58]
mqtt-spy-0.4.0-beta-b10-jar-with-dependencies.jar

When attempting to run a test case from within MQTT spy, the following exception occurs:

 2016-01-22 10:27:54,168 ERROR [SpyUncaughtExceptionHandler   ]  - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.NullPointerExc
eption: Input stream must not be null
java.lang.NullPointerException: Input stream must not be null
        at javafx.scene.image.Image.validateInputStream(Unknown Source)
        at javafx.scene.image.Image.<init>(Unknown Source)
        at pl.baczkowicz.mqttspy.ui.TestCaseExecutionController.getIconForStatus(TestCaseExecutionController.java:250)
        at pl.baczkowicz.mqttspy.ui.TestCaseExecutionController$2$1.updateItem(TestCaseExecutionController.java:127)
        at pl.baczkowicz.mqttspy.ui.TestCaseExecutionController$2$1.updateItem(TestCaseExecutionController.java:119)
        at javafx.scene.control.TableCell.updateItem(Unknown Source)
        at javafx.scene.control.TableCell.layoutChildren(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Parent.layout(Unknown Source)
        at javafx.scene.Scene.doLayoutPass(Unknown Source)
        at javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
        at com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by kamilfb** [comment]
Many thanks for reporting this - should be fixed in 0.4.0 beta build 12. Please check if that's any good now.

**Comment by kamilfb** [comment]
Fix released in v0.4.0.
