### ISSUE TITLE
InvalidKeyException

### ISSUE THREAD

**Issue by RickorDD** [kamilfb/mqtt-spy#63]
**0.4.0 (build 4) and (build 12) have InvalidKeyException.**
**Testing with AWS Account and Java 1.8.0_71**

**mqtt-spy.log**

2016-02-05 13:25:17,007 INFO  [JavaFX Application Thread     ] [MqttConfigurationUtils        ]  - Auto-complete for server URI (A3N80655B02D7L.iot.eu-west-1.amazonaws.com -> ssl://A3N80655B02D7L.iot.eu-west-1.amazonaws.com)
2016-02-05 13:25:17,012 ERROR [JavaFX Application Thread     ] [ConnectionManager             ]  - Cannot create connection properties
pl.baczkowicz.spy.exceptions.ConfigurationException: Invalid configuration parameters
	at pl.baczkowicz.mqttspy.connectivity.MqttConnectionDetailsWithOptions.<init>(MqttConnectionDetailsWithOptions.java:91)
	at pl.baczkowicz.mqttspy.connectivity.RuntimeConnectionProperties.<init>(RuntimeConnectionProperties.java:34)
	at pl.baczkowicz.mqttspy.ui.connections.ConnectionManager.openConnection(ConnectionManager.java:156)
	at pl.baczkowicz.mqttspy.ui.ControlPanelController$3.handle(ControlPanelController.java:306)
	at pl.baczkowicz.mqttspy.ui.ControlPanelController$3.handle(ControlPanelController.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.scene.control.Button.fire(Unknown Source)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.scene.Scene$MouseHandler.access$1500(Unknown Source)
	at javafx.scene.Scene.impl_processMouseEvent(Unknown Source)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: pl.baczkowicz.spy.exceptions.SpyException: Cannot create TLS/SSL connection
	at pl.baczkowicz.spy.security.SecureSocketFactoryBuilder.getSocketFactory(SecureSocketFactoryBuilder.java:100)
	at pl.baczkowicz.mqttspy.connectivity.MqttConnectionDetailsWithOptions.populateMqttConnectOptions(MqttConnectionDetailsWithOptions.java:175)
	at pl.baczkowicz.mqttspy.connectivity.MqttConnectionDetailsWithOptions.<init>(MqttConnectionDetailsWithOptions.java:87)
	... 59 more
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(Unknown Source)
	at java.security.KeyFactory.generatePrivate(Unknown Source)
	at pl.baczkowicz.spy.security.SecureSocketUtils.loadPrivateKeyFromPemFile(SecureSocketUtils.java:96)
	at pl.baczkowicz.spy.security.SecureSocketUtils.getKeyManagerFactory(SecureSocketUtils.java:185)
	at pl.baczkowicz.spy.security.SecureSocketFactoryBuilder.getSocketFactory(SecureSocketFactoryBuilder.java:93)
	... 61 more
Caused by: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.pkcs.PKCS8Key.decode(Unknown Source)
	at sun.security.pkcs.PKCS8Key.decode(Unknown Source)
	at sun.security.rsa.RSAPrivateCrtKeyImpl.<init>(Unknown Source)
	at sun.security.rsa.RSAPrivateCrtKeyImpl.newKey(Unknown Source)
	at sun.security.rsa.RSAKeyFactory.generatePrivate(Unknown Source)
	... 66 more

**Comment by kamilfb** [comment]
Any chance you could attach the configuration file you are using? I'd like to see which TLS/SSL mode you are using. Also, did you say you got it working with MQTT.fx?

**Comment by kamilfb** [comment]
I might have identified the problem - could you try http://tinyurl.com/mqtt-spy-download/mqtt-spy-0.5.0-beta-b5-jar-with-dependencies.jar ?

**Comment by RickorDD** [comment]
0.5.0 the same error
what is with PKCS8 and PKCS1?

Caused by: java.security.InvalidKeyException: invalid key format
	at sun.security.pkcs.PKCS8Key.decode(Unknown Source)

My (AWS) Key begin with "-----BEGIN RSA PRIVATE KEY-----"
I tested with "-----BEGIN PRIVATE KEY-----" the same error.

**Comment by RickorDD** [comment]
Update 0.5.0 is connected.
and another proposal to improve:
"Client key password" need a value although AWS needs none

**Comment by kamilfb** [comment]
Hi @RickorDD! Is it working now as expected? Can to connect to AWS correctly now?

**Comment by RickorDD** [comment]
yes 0.5.0 beta (build 5) running fine with AWS

**Comment by kamilfb** [comment]
Awesome! Thanks for confirming. Could you also explain further the client key password issue? Does it fail when you leave it empty?

**Comment by RickorDD** [comment]
One more note
“Client key in PEM format” is Yes

And i checked again with empty “Client key password” and now its running.
So it should be good.

**Comment by kamilfb** [comment]
Many thanks @RickorDD for raising it in the first place and retesting it with the beta version. I'm glad we managed to get it sorted. Cheers!

**Comment by kamilfb** [comment]
If anyone wants to stick to v0.4.0 instead of v0.5.0 beta then putting the key to a keystore should get it working.
